### ISSUE TITLE
Support fields with types that do not implement PartialEq

### ISSUE THREAD

**Issue by PPakalns** [tim-harding/soa-rs#10]
Test that doesn't pass:

```rs
#[test]
fn field_type_without_partial_eq() {
    // Type that doesn't implement PartialEq
    struct TypeWithoutPartialEq {
        foo: u8,
    }

    #[derive(Soars)]
    struct Example {
        a: TypeWithoutPartialEq,
    }
    let arr = soa![Example {
        a: TypeWithoutPartialEq { foo: 1 }
    }];
    assert_eq!(arr.get(0).unwrap().a.foo, 1);
}
```

If PartialEq derives are added, then this test passes. It shouldn't be required.

Tried to fix this in https://github.com/tim-harding/soa-rs/pull/8/files , but pull request was closed even if the existing PartialEq implementation in derive macro for #itemRef was made conditional (kept the same) based on soa_derive.

This heavily limits what types can be stored in Soa.

**Comment by tim-harding** [comment]
This clarifies the issue. I am publishing 0.4.0 that passes this test.
