### ISSUE TITLE
Support serde serialization, deserialization

### ISSUE THREAD

**Issue by PPakalns** [tim-harding/soa-rs#11]
Support serde serialization and deserialization of soa_rs::Soa. 

Implementation could be added if #[soa_serde] attribute is added to the struct. It would require that all fields are serializable, deserializable.

This would be useful when data needs to be passed around and no conversion between Vec<T> and soa_rs::Soa<T> would be needed.

**Comment by tim-harding** [comment]
Added in 0.5.0.
