### ISSUE TITLE
Serde serialization defaults to "array of structs" and is not configurable

### ISSUE THREAD

**Issue by stfnp** [tim-harding/soa-rs#16]
When using the `serde` feature and serializing an `Soa<...>` type, the result is an array of structs. As JSON, for example, it might look something like this:

    [
        {
            "a": ...,
            "b": ...,
            "c": ...
        },
        {
            "a": ...,
            "b": ...,
            "c": ...
        },

        ...
    ]

Unfortunately this adds quite some size overhead because the field names are repeated for each entry in the array.
Would it be possible to make the data representation for serialization configurable between SoA and AoS?

**Edit:** The desired result for me would look like this, a struct of arrays with only one field name, followed by the respective data:

    {
        "a": [..., ..., ...],
        "b": [..., ..., ...],
        "c": [..., ..., ...]
    }

**Comment by tim-harding** [comment]
After looking into it a bit, I can't see how I would make it work. If need be, you could wrap the container for serialization so that each of the slices gets serialized separately. Deserializing would involve first deserializing to `Vec`s for each field, then building each element and pushing it into the `Soa`. Probably not worth the hassle.

**Comment by stfnp** [comment]
Thank you for your suggestions! Your first understanding was exactly right. In my application I'm serializing some numerical time-series data to a binary format (MessagePack), that's why the size of the field names, when repeated for each time sample, is significant when compared to the actual data. But I also want to keep the field names as they are to keep the data self-descriptive. So I will probably follow your first suggestion and implement the (de)serialization myself.
